describe('Basic info', function() {
	it('Finds and retrieves basic info', function() {
		cy.visit('http://localhost')
		cy.get('#email').type('asdf')
		cy.get('#password').type('asdf')
		cy.get('span:contains("Sisene")').click()
		cy.wait(120000)
		cy.get('#first_name').type('Pille')
		cy.get('span:contains("Otsi")').click()
		cy.get('td:contains("PAGAN")').click()
		cy.get('#national_id').should('have.value', '47102042742')
	})
})

describe('Info modification', function() {
	it('Changes information', function() {
		cy.visit('http://localhost')
		cy.get('#email').type('asdf')
		cy.get('#password').type('asdf')
		cy.get('span:contains("Sisene")').click()
		cy.get('#first_name').type('Pille')
		cy.get('span:contains("Otsi")').click()
		cy.get('td:contains("PAGAN")').click()
		cy.get('span:contains("MUUDA ISIKUANDMEID")').click()
		cy.wait(3000)
		cy.get('#phone').type('{selectall}').type('12345')
		cy.get('span:contains("SALVESTA")').click()
		cy.get('p:contains(" Logi välja ")').click()
		cy.visit('http://localhost')
		cy.get('#email').type('asdf')
		cy.get('#password').type('asdf')
		cy.get('span:contains("Sisene")').click()
		cy.get('#first_name').type('Pille')
		cy.get('span:contains("Otsi")').click()
		cy.get('td:contains("PAGAN")').click()
		cy.get('#phone').should('have.value', '12345')
		cy.get('span:contains("MUUDA ISIKUANDMEID")').click()
		cy.get('#phone').type('{selectall}').type('3725074194')
		cy.get('span:contains("SALVESTA")').click()
	})
})