CREATE OR REPLACE TABLE sessions
(id INT AUTO_INCREMENT PRIMARY KEY,
incident_id INT NOT NULL, FOREIGN KEY (incident_id) REFERENCES incidents (id) ON DELETE CASCADE ON UPDATE CASCADE,
kuupaev DATE NOT NULL,
kirjeldus VARCHAR(64) NOT NULL,
sidevahendid BOOL NOT NULL,
kriisinoustamine DECIMAL(5,2) NOT NULL,
kriisinoustamise_aeg ENUM('teadmata', '08:00-22:00', '22:00-08:00') NOT NULL,
juhtuminoustamine DECIMAL(5,2) NOT NULL,
vorgustikutoo DECIMAL(5,2) NOT NULL,
psuhhonoustamine DECIMAL(5,2) NOT NULL,
juuranoustamine DECIMAL(5,2) NOT NULL,
tegevused_lapsega DECIMAL(5,2) NOT NULL,
tugiteenused DECIMAL(5,2) NOT NULL,
naise_majutus TINYINT NOT NULL,
laste_arv TINYINT NOT NULL,
laste_majutus TINYINT NOT NULL,
umarlaud BOOL NOT NULL,
marac BOOL NOT NULL,
perearst_kaasatud BOOL NOT NULL,
emo_kaasatud BOOL NOT NULL,
naistearst_kaasatud BOOL NOT NULL,
politsei_kaasatud BOOL NOT NULL,
prokuratuur_kaasatud BOOL NOT NULL,
ohvriabi_kaasatud BOOL NOT NULL,
lastekaitse_kaasatud BOOL NOT NULL,
kov_kaasatud BOOL NOT NULL,
tsiviilkohus_kaasatud BOOL NOT NULL,
kriminaalkohus_kaasatud BOOL NOT NULL,
haridusasutus_kaasatud BOOL NOT NULL,
mtu_kaasatud BOOL NOT NULL,
tuttavad_kaasatud BOOL NOT NULL,
markused TEXT NOT NULL,
muutja VARCHAR(64),
muutmisaeg DATE);